apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iygl1alus-python 
  janus-idp.io/tekton: iygl1alus-python
  backstage.io/kubernetes-id: iygl1alus-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iygl1alus-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  